make install-service-dhclient
make install-service-dhcpcd
make install-service-bridge
make install-service-ipx
make install-service-pppoe
make install-service-wpa
make install-accounts-daemon
make install-acpid
make install-alsa
make install-httpd
make install-php
make install-autofs
make install-atd
make install-avahi
make install-bind
make install-bluetooth
make install-cups
make install-saslauthd
make install-dbus
make install-dovecot
make install-wicd
make install-dhcpd
make install-exim
make install-fcron
make install-firewalld
make install-gdm
make install-gpm
make install-haveged
make install-heimdal
make install-iptables
make install-krb5
make install-lprng
make install-lxdm
make install-mysql
make install-netfs
make install-networkmanager
make install-nfs-client
make install-nfs-server
make install-ntpd
make install-slapd
make install-postfix
make install-postgresql
make install-proftpd
make install-random
make install-rpcbind
make install-rsyncd
make install-samba
make install-lightdm
make install-sendmail
make install-smartd
make install-soprano
make install-swat
make install-sshd
make install-stunnel
make install-svn
make install-git-daemon
make install-sysstat
make install-unbound
make install-virtuoso
make install-vsftpd
make install-winbindd
make install-xinetd
